### PR TITLE
Add --dane option to validate TLSA records

### PR DESCRIPTION
**Pull request by dilyanpalauzov**
Examples:
```
./check_ssl_cert --dane=211  --port 25 -P smtp -H hummus.csx.cam.ac.uk
./check_ssl_cert --dane=311  --port 25 -P smtp -H mail.ietf.org
./check_ssl_cert --dane=311  -H www.ietf.org
./check_ssl_cert --dane=301 --rsa  -H mail.aegee.org
./check_ssl_cert --dane=301 --ecdsa  -H mail.aegee.org
./check_ssl_cert --dane=302 --rsa  -H mail.aegee.org
./check_ssl_cert --dane=302 --ecdsa  -H mail.aegee.org
```

### CODE REVIEW

**Comment by matteocorti** [comment]
Thanks. I still have problems on macOS

```
$ delv +short TLSA _25._tcp.hummus.csx.cam.ac.uk
;; none:29: no crypto support
delv: No trusted keys were loaded
```

I will take a look as soon as I find some time

**Comment by dilyanpalauzov** [comment]
Both https://www.huque.com/bin/danecheck-smtp and  https://dane.sys4.de/smtp report for domain exim.org that the TLSA record `2 1 1 60B87575447DCBA2A36B7D11AC09FB24A9DB406FEE12D2CC90180517 616E8A18` is valid and `2 1 1 B111DD8A1C2091A89BD4FD60C57F0716CCE50FEEFF8137CDBEE0326E 02CF362B` is invaid, both from `TLSA _25._tcp.hummus.csx.cam.ac.uk`.

**Comment by matteocorti** [comment]
I don't say that the logic is not working, but the output of `delv` should be processed. 

At the moment I just get:

```
$ ./check_ssl_cert --dane=311  --port 25 -P smtp -H mail.ietf.org
;; none:29: no crypto support
delv: No trusted keys were loaded
No TLSA records found at _25._tcp.mail.ietf.org
```

Which is not very useful

**Comment by dilyanpalauzov** [comment]
Maybe “no crypto support” means, that delv was not compiled properly.

DANE expects working DNSSEC and delv verifies that DNSSEC is working.

If instead `DANE=$(dig +noall +noclass +nottlid +answer TLSA _$PORT._tcp.$HOST|sed "s/.*TLSA[ \t]\(.*\)/-dane_tlsa_rrdata \'\1\' /"|grep "X Y Z"|tr -d '\n')` is used, then the script  is more portable, but DNSSEC is not validated.

**Comment by matteocorti** [comment]
It could be. I get the same error on macOS and Fedora. On which system did you get it working? I tried with `delv 9.10.6` and `delv 9.11.11-RedHat-9.11.11-1.fc30`.

We could leave the implementation with `delv` and just check if it is working by checking the output.

**Comment by dilyanpalauzov** [comment]
On my Linuxes from Scratch it works, both delv 9.12.0 and 9.14.6.

**Comment by matteocorti** [comment]
I'll take a look tomorrow

**Comment by matteocorti** [comment]
An option would be to check if `delv` is working and use it. If not fall back to `dig`. But to test I need to find an environment where `delv` is working.

**Comment by dilyanpalauzov** [comment]
`drill -D` from libldns coud also be used to validate DNSSEC, but at the end either check_ssl_cert has to support many DNS inspection tools, or the users will be required to install a specific tool and bring it running on the system.

**Comment by matteocorti** [comment]
I checked several distributions and did not find a working one. As almost nobody goes for a scratch solution, I will integrate the check with dig

**Comment by matteocorti** [comment]
Some of the errors are caused by a strange behaviour on macOS

```
dig +noall +noclass +nottlid +answer TLSA _25._tcp.mail.ietf.org   | hexdump -C
00000000  5f 32 35 2e 5f 74 63 70  2e 6d 61 69 6c 2e 69 65  |_25._tcp.mail.ie|
00000010  74 66 2e 6f 72 67 2e 09  54 4c 53 41 09 33 20 31  |tf.org..TLSA.3 1|
00000020  20 31 20 30 43 37 32 41  43 37 30 42 37 34 35 41  | 1 0C72AC70B745A|
00000030  43 31 39 39 39 38 38 31  31 42 31 33 31 44 36 36  |C19998811B131D66|
00000040  32 43 39 41 43 36 39 44  42 44 42 45 37 43 42 32  |2C9AC69DBDBE7CB2|
00000050  33 45 35 42 35 31 34 42  35 36 36 20 36 34 43 35  |3E5B514B566 64C5|
00000060  44 33 44 36 0a                                    |D3D6.|
00000065
```

The character after TLSA ist indeed a tab

But ` sed 's/.*TLSA[\ \t]/-dane_tlsa_rrdata /'` ignores it.

The same on Linux works without problems

**Comment by dilyanpalauzov** [comment]
On my system `sed "s/.*TLSA[ \t]\(.*\)/-dane_tlsa_rrdata\'\1\' /"` does work.

I found a new option for dig:

`dig +short  TLSA _25._tcp.mail.aegee.org` returns
```
3 0 1 BEAC45EB31CB044531757F3A8683F47F1BBEFB7262163D9F0D4B319B 5848998D
3 0 2 08A2D79628DDBBA20260CC1630E9E75FC303FE1BD308AFBAF799EBE7 28CFEE8F1577893813E908F45C9885138C185D84A5534502BFCA0177 E52D4F9D4D6640E2
3 1 1 2D1E4DDD0F7764423B1D6C62D41A324C71863BB8A4D71701B91FA126 CD5D457D
```
Since there is no TLSA in the output, the sign after it does not matter.

**Comment by matteocorti** [comment]
On my Linux systems it works too. On macOS Catalina not. But I suppose it's a bug

**Comment by dilyanpalauzov** [comment]
`DIG_RESULT=$(dig +short TLSA _$PORT._tcp.$HOST|sed "s/\(.*\)/-dane_tlsa_rrdata \'\1\' /"|tr -d '\n')`

**Comment by dilyanpalauzov** [comment]
Or, without `sed` and `tr`:

`DIG_RESULT=$(dig +short TLSA _$PORT._tcp.$HOST|while read L; do echo -n " -dane_tlsa_rrdata '$L' "; done)`

**Comment by matteocorti** [comment]
`echo -n` is not posix. But is not needed anyway otherwise the grep will not work. Thanks

**Pull request merged**
