### PR TITLE
Add LDAPS support & minor documentation fixes

### PR DESCRIPTION
**Pull request by matsimon**
While LDAP with StartTLS has been supported by check_ssl_cert for a while (requires OpenSSL 1.1.1 or newer), LDAPS wasn't and is actually a trivial one.

Meanwhile I've discovered a a typo I have introduced myself in 505d63493e0a0ca82328f2f2a6ca15a89b11efa8 and saw that the manpage and help output have gotten a bit out of sync. Are you OK with having alphabetical ordering in the options?

Finally I've removed some trailing whitespace while I was at it.

The only remaining issue is that I was unable to put a line break in the updated manpage section where the information about StartTLS might be more legible if it were put on new line. I'm not much into groff and inserting .br didn't work for me here.

### CODE REVIEW

**Comment by matteocorti** [comment]
Thanks!

**Comment by matsimon** [comment]
Thank you Matteo, any idea how to get those line breaks in the manpage?

**Comment by matteocorti** [comment]
Somehow I did something wrong with the merge (some files are still old)

**Comment by matteocorti** [comment]
I committed the missing files and the tests are OK again.

**Comment by matteocorti** [comment]
About the line breaks: do you mean After the list of the protocols and "These protocols"?

**Comment by matsimon** [comment]
Yes, exactly: https://github.com/matteocorti/check_ssl_cert/blob/a90da0b92b7da3e8cca9b4e98c8490e472524419/check_ssl_cert.1#L131

I didn't manage inserting anything that would result into a line break without messing up rendering of the manpage otherwise.

**Comment by matteocorti** [comment]
In my case it work with a .br (lowercase) (macOS)

**Comment by matteocorti** [comment]
Does not work on Linux

**Comment by matteocorti** [comment]
Sorry I was wrong. Works also on Linux

**Comment by matsimon** [comment]
Interesting, if I insert it this way...
```patch
diff --git a/check_ssl_cert.1 b/check_ssl_cert.1
index a7d4d90..67379ec 100644
--- a/check_ssl_cert.1
+++ b/check_ssl_cert.1
@@ -128,7 +128,8 @@ path of the openssl binary to be used
 TCP port
 .TP
 .BR "-P,--protocol" " protocol"
-use the specific protocol: ftp, http (default), imap, imaps, irc, ldap, ldaps, pop3, pop3s, smtp, xmpp. These protocols switch to TLS using StartTLS: ftp, imap, ldap, pop3, smtp.
+use the specific protocol: ftp, http (default), imap, imaps, irc, ldap, ldaps, pop3, pop3s, smtp, xmpp.
+.br These protocols switch to TLS using StartTLS: ftp, imap, ldap, pop3, smtp.
 .TP
 .BR "-s,--selfsigned"
```
... GNU groff 1.22.3 on Debian renders as follows:
```man
       -P,--protocol protocol
              use  the  specific  protocol:  ftp, http (default), imap, imaps,
              irc, ldap, ldaps, pop3, pop3s, smtp, xmpp.
```

It simply removes all the text on the next line. But as I indicated: I am really not familiar with groff at all so I may be attempting something completely off... sorry for bothering you with such issues :-\

**Comment by matteocorti** [comment]
I noticed the same on BSD. If the .br is alone then it seems to work

```
.BR "-P,--protocol" " protocol"
use the specific protocol: ftp, http (default), imap, imaps, irc, ldap, ldaps, pop3, pop3s, smtp, xmpp.
.br
These protocols switch to TLS using StartTLS: ftp, imap, ldap, pop3, smtp.

```

renders as

```
       -P,--protocol protocol
              use the specific protocol: ftp, http (default), imap, imaps, irc, ldap, ldaps, pop3, pop3s, smtp, xmpp.
              These protocols switch to TLS using StartTLS: ftp, imap, ldap, pop3, smtp.
```

**Pull request merged**
