### PR TITLE
Add support for IRC protocol check

### PR DESCRIPTION
**Pull request by DerDakon**
Also fix protocol error in SMTP protocol check.

### CODE REVIEW

**Comment by matteocorti** [comment]
Thanks, is there a public IRC server I could include in the tests?

**Comment by DerDakon** [comment]
Depends on how often you want to call it. If it's only every once in a a while then try irc2.feuerwehrmann.de for the moment.

**Comment by matteocorti** [comment]
Hi

if it could be a performance problem I will just keep in mind for casual testing but I will not include a test in the test suite.

Thanks

Matteo

> On 15 Jun 2016, at 18:45 , Rolf Eike Beer <notifications@github.com> wrote:
> 
> Depends on how often you want to call it. If it's only every once in a a while then try irc2.feuerwehrmann.de for the moment.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub <https://github.com/matteocorti/check_ssl_cert/pull/16#issuecomment-226247166>, or mute the thread <https://github.com/notifications/unsubscribe/AFu6kAOMDHoRRZ0xGa8jftvpwl6SqCsjks5qMCwQgaJpZM4I2jCO>.
> 

-- 
Matteo Corti
http://corti.li

**Comment by DerDakon** [comment]
If it's every few hours this will be far from a performance problem.

**Pull request merged**
