### PR TITLE
handle wildcard certificates

### PR DESCRIPTION
**Pull request by sshmanko**
Suggestion how to handle wildcard certificates.
First it strips 1st character from CN value - asterisk, then in looks for that value in argument specified for the check.

### CODE REVIEW

**Comment by matteocorti** [comment]
Thanks. Do you habe a couple of public examples I could test?

**Comment by sshmanko** [comment]
Sure, here is how I tested:
./check_ssl_cert -H translate.google.com -c 60 -n translate.google.com
SSL_CERT OK - X.509 certificate for '*.google.com' from 'Google Internet Authority G2' valid until Jun  7 00:00:00 2016 GMT (expires in 79 days)|days=79;;60;;
Some more domains:
en.wikipedia.orgapi.twilio.comicehd.videobet.com
Thanks,Sergei
Date: Sat, 19 Mar 2016 02:53:16 -0700

**Comment by matteocorti** [comment]
Seems more or less to work but I will have to check since

./check_ssl_cert -H translate.google.com -n 'agoogle.com'
SSL_CERT OK - X.509 certificate for '*.google.com' from 'Google Internet Authority G2' valid until Jun  7 00:00:00 2016 GMT

**Comment by sshmanko** [comment]
Good fix, just wanted to propose to match beginning of the line, but I see you just did that.

**Pull request merged**
