### PR TITLE
Fix validity date and LANG

### PR DESCRIPTION
**Pull request by grizzlydev-sarl**
In my previous PR, I hadn't noticed that you had introduced the "hours_until" function. 
I made some changes to use it. 
This PR also contains a fix for the LANG that's used during the process : set it once and for all.

### CODE REVIEW

**Comment by Darwiner** [comment]
This new setting of LC_ALL is generating an error on my end, on Linux (CentOS 7.4.x).  Working properly without any errors before that with release 1.114.0.

Master:

```
$ ./check_ssl_cert -H www.google.com
./check_ssl_cert: line 29: warning: setlocale: LC_ALL: cannot change locale (en_US): No such file or directory
SSL_CERT OK - x509 certificate 'www.google.com' from 'GTS CA 1O1' valid until Aug 12 12:08:31 2020 GMT (expires in 68 days)|days_chain_elem1=68;20;15;; days_chain_elem2=558;20;15;;
```

1.114.0:

```
./check_ssl_cert -H www.google.com
SSL_CERT OK - x509 certificate 'www.google.com' from 'GTS CA 1O1' valid until Aug 12 12:08:31 2020 GMT (expires in 68 days)|days=68;;;;
$ ./check_ssl_cert -H www.google.com -V
check_ssl_cert version 1.114.0
```

**Comment by grizzlydev-sarl** [comment]
@Darwiner Sorry about that. What does `cat /etc/sysconfig/i18n`, `locale` and `locale -a` say ?
The first is the system language, the second is the current language settings, and the third lists all the available languages on the system.

Ultimately, I guess the best way to deal with this would be to use `LC_ALL=C` instead of `LC_ALL=en_US` since not everyone has en_US installed on their system.

(and sorry @matteocorti  for the messy PR :-/ )

**Comment by matteocorti** [comment]
Thanks for the patches. I released a new version along with a fix for feature request #199

**Comment by grizzlydev-sarl** [comment]
Terrific, thanks a lot!

**Comment by Darwiner** [comment]
> @Darwiner Sorry about that. What does `cat /etc/sysconfig/i18n`, `locale` and `locale -a` say ?
> The first is the system language, the second is the current language settings, and the third lists all the available languages on the system.
> 
> Ultimately, I guess the best way to deal with this would be to use `LC_ALL=C` instead of `LC_ALL=en_US` since not everyone has en_US installed on their system.
> 
> (and sorry @matteocorti for the messy PR :-/ )

Looks to be ok now with LC_ALL being set to C.  Thanks. :)

For the record, what I have on my end:

```
$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_CA.UTF-8
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"
LC_ALL=

$ locale -a
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
POSIX
en_US.utf8
```

**Comment by grizzlydev-sarl** [comment]
@Darwiner as you can see, you have only C, POSIX and en_US.utf8 installed on your system and your system seems to be configured to use en_ca.utf8. Hence, the errors that appear on each command.
One way to fix this is to edit /etc/sysconfig/i18n (eg https://blog.earth-works.com/2014/02/10/fixing-lc-locale-issues-in-centos-and-rhel/ )

**Pull request merged**
