### PR TITLE
with -f you can not only pass a x509 certificate file but also a certificate revocation list (CRL) to check validity period

### PR DESCRIPTION
**Pull request by booboo-at-gluga-de**
For authenticating my clients when connecting to my infrastructure I run an own CA. For revoking certificates I use a certificate revocation list (CRL). And the CRL file has a limited validity period which I want to check within my monitoring system. So I extended check_ssl_cert to work with CRL files too.

I guess this could be helpful for others, too.

### CODE REVIEW

**Comment by matteocorti** [comment]
Hi thanks for the suggestion. I will take a look but I will most likely add an additional option (having the same command line options with different semantics is not really ideal).

**Comment by matteocorti** [comment]
Sorry my mistake, I was thinking about the -r option. -f makes sense...

**Comment by booboo-at-gluga-de** [comment]
Thanks a lot for the quick and uncomplicated handling of the pull request!

**Comment by matteocorti** [comment]
Thanks to you for the enhancements!!!

**Pull request merged**
