### PR TITLE
Add UTF-8 Support

### PR DESCRIPTION
**Pull request by k0ste**
Add utf8 support for CN resolution and for long-output. May be missing for something options, because I don't use all options.

```bash
./check_ssl_cert -H localhost -w 30 -c 3 -f nevermind.pem -i 'COMODO RSA Domain Validation Secure Server CA' -n 'е2е4онлайн.рф'
SSL_CERT CRITICAL \xD0\xB52\xD0\xB54\xD0\xBE\xD0\xBD\xD0\xBB\xD0\xB0\xD0\xB9\xD0\xBD.\xD1\x80\xD1\x84: invalid CN ('\xD0\xB52\xD0\xB54\xD0\xBE\xD0\xBD\xD0\xBB\xD0\xB0\xD0\xB9\xD0\xBD.\xD1\x80\xD1\x84' does not match 'е2е4онлайн.рф')|days=882;30;3;;
```

```bash
 ./check_ssl_cert -H localhost -w 30 -c 3 -f nevermind.pem -i 'COMODO RSA Domain Validation Secure Server CA' -n 'е2е4онлайн.рф'
SSL_CERT OK - X.509 certificate for 'е2е4онлайн.рф' from 'COMODO RSA Domain Validation Secure Server CA' valid until Aug  2 23:59:59 2018 GMT (expires in 882 days)|days=882;30;3;;
```

```bash
./check_ssl_cert -H localhost -f nevermind.pem --long-output subject --ignore-sig-alg -n 'Мельников Андрей Александрович'
SSL_CERT CRITICAL \xD0\x9C\xD0\xB5\xD0\xBB\xD1\x8C\xD0\xBD\xD0\xB8\xD0\xBA\xD0\xBE\xD0\xB2 \xD0\x90\xD0\xBD\xD0\xB4\xD1\x80\xD0\xB5\xD0\xB9 \xD0\x90\xD0\xBB\xD0\xB5\xD0\xBA\xD1\x81\xD0\xB0\xD0\xBD\xD0\xB4\xD1\x80\xD0\xBE\xD0\xB2\xD0\xB8\xD1\x87: invalid CN ('\xD0\x9C\xD0\xB5\xD0\xBB\xD1\x8C\xD0\xBD\xD0\xB8\xD0\xBA\xD0\xBE\xD0\xB2 \xD0\x90\xD0\xBD\xD0\xB4\xD1\x80\xD0\xB5\xD0\xB9 \xD0\x90\xD0\xBB\xD0\xB5\xD0\xBA\xD1\x81\xD0\xB0\xD0\xBD\xD0\xB4\xD1\x80\xD0\xBE\xD0\xB2\xD0\xB8\xD1\x87' does not match 'Мельников Андрей Александрович')\nsubject: \xD0\x9C\xD0\xB5\xD0\xBB\xD1\x8C\xD0\xBD\xD0\xB8\xD0\xBA\xD0\xBE\xD0\xB2 \xD0\x90\xD0\xBD\xD0\xB4\xD1\x80\xD0\xB5\xD0\xB9 \xD0\x90\xD0\xBB\xD0\xB5\xD0\xBA\xD1\x81\xD0\xB0\xD0\xBD\xD0\xB4\xD1\x80\xD0\xBE\xD0\xB2\xD0\xB8\xD1\x87
```

```bash
./check_ssl_cert -H localhost -f nevermind.pem --long-output subject --ignore-sig-alg -n 'Мельников Андрей Александрович'
SSL_CERT OK - X.509 certificate for 'Мельников Андрей Александрович' from 'CA Promsvyazbank PJSC' valid until Mar  2 05:46:57 2017 GMT\nsubject:  Мельников Андрей Александрович
```

For me works as expect.

### CODE REVIEW

**Comment by matteocorti** [comment]
Hi the patch ist from an old version and will revert other parts of the code. I will merge manually. Thanks!

**Comment by matteocorti** [comment]
I patched the two lines manually leaving the SSL Labs handling untouched.
Thanks again

**Comment by k0ste** [comment]
@matteocorti, you miss sed string, it's important. Not it's not work.

**Comment by matteocorti** [comment]
Sorry should be fixed

**Pull request closed without merging**
