### PR TITLE
Remove trailing spaces, convert tabs to spaces

### PR DESCRIPTION
**Pull request by szepeviktor**
@matteocorti Would you be interested in formatting case statements like this?
```bash
case "$1" in
    --no_ssl2)
        SSL_VERSION_DISABLED+=" -no_ssl2"
        shift
        ;;
esac
```

### CODE REVIEW

**Comment by matteocorti** [comment]
Not really sure which shells support "+=", I did not find anything in the POSIX specs

**Comment by szepeviktor** [comment]
Yes.
```shell
#!/bin/dash

A="one"
A+=" and one"

echo "$A"
```

```
./dash.sh
./dash.sh: 4: ./dash.sh: A+= and one: not found
```

But I am a Bashist.

**Comment by szepeviktor** [comment]
> Not really sure which shells support "+=", I did not find anything in the POSIX specs

I am thinking about code styling.

**Comment by matteocorti** [comment]
Style is OK (is nicer), I would just avoid +=

**Pull request merged**
