### PR TITLE
Wrapping some (too) long lines in help.

### PR DESCRIPTION
**Pull request by booboo-at-gluga-de**
The output of "check_ssl_cert --help" contained some very long lines.
This causes trouble:
   * If executed on terminals with limited size, the information
     is hard too read.
   * In the README.md as displayed on GitHub, some information
     is being cut off (and the user needs to scroll horizontally
     to read the full information) - this is deemed uncomfortable
     fot the user.

### CODE REVIEW

**Comment by matteocorti** [comment]
Thanks!

**Comment by matteocorti** [comment]
I followed you advice and shortened everything to the canonical 78 characters

**Comment by booboo-at-gluga-de** [comment]
Hi Matteo,

to be honest: I (personally) wouldn't have been **that** strict. I had more the pragmatic approach in mind (every line length fitting into a terminal which is nowadays available somewhere "in the wild" and everything fitting into GitHub's representation of the README file would have been suggested to be OK). 
But I absolutely agree: With 78 you are always for 100% safe!

Thanks a lot!

**Comment by matteocorti** [comment]
Hi Bernd

I know, 78 is a little old-fashioned, but so it's even readable on my mobile phone :-)

Matteo

**Pull request merged**
