### PR TITLE
Check all chain elements

### LINKED ISSUE #200: Checking all supplied chain certificates
**Is your feature request related to a problem? Please describe.**

We use several wildcard certificates, that are also signed by a ~~now expired~~ renewed CA, where the old certificate version is shipped in the chain.

Basically OpenSSL seems to handle this correctly, but other TLS implementations can break when checking the presented chain certificate.

A write up:
https://ohdear.app/blog/resolving-the-addtrust-external-ca-root-certificate-expiration

**Describe the solution you'd like**

I guess it would be great when we check all the presented chain certificates for trust, and at least warn, if one of them is not valid or trusted.

---

This is merely a suggestion, to start discussion and here thoughts from the community.

### PR DESCRIPTION
**Pull request by grizzlydev-sarl**
Fixes #200 
Actually there's three things here :
- check all elements of a chain ;
- reduce code duplication and avoid having too many if/then for the verbose/debug output ;
- consistent indentation of 4 space.

### CODE REVIEW

**Comment by grizzlydev-sarl** [comment]
Two things could be improved : 
- the way prepend_critical_message() is designed, we can't add more performance data if the function is not called again. The performance with the result string at this point, but later on, right when the plugin outputs the result.
- critical() and warning() should not print stuff after the performance data.

**Comment by matteocorti** [comment]
Thanks

**Comment by matteocorti** [comment]
Seems not to work on BSD (macOS), I'll take a look

**Comment by Darwiner** [comment]
FWIW, seems to be working correctly on my end on macOS.

```
./check_ssl_cert -H www.github.com -w 3200                                                        1 ✘  18:47:09 
SSL_CERT WARN github.com: x509 certificate element 1 will expire in 705 day(s) on May 10 12:00:00 2022 GMT|days_chain_elem1=705;3200;;;
Error(s):
    SSL_CERT WARN github.com: x509 certificate element 1 will expire in 705 day(s) on May 10 12:00:00 2022 GMT|days_chain_elem1=705;3200;;;
    SSL_CERT WARN github.com: x509 certificate element 2 will expire in 3062 day(s) on Oct 22 12:00:00 2028 GMT|days_chain_elem1=705;3200;;; days_chain_elem2=3062;3200;;;
```

**Comment by grizzlydev-sarl** [comment]
I thought I screwed up for a moment, but I tried with some of the older versions of the script and the result is the same.
I'm on macOS HighSierra 10.13.2

@Darwiner what macOS version are you using ?

**Comment by Darwiner** [comment]
@grizzlydev-sarl I'm on 10.15.2.
```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.2
BuildVersion:   19C57
```

Not getting any issue neither when running:
`openssl s_client -connect www.google.com:443 -showcerts -verify 6`

As for openssl...
```
$ openssl version
LibreSSL 2.8.3
```

**Comment by grizzlydev-sarl** [comment]
Thanks. That confirms what I suspected : the culprit is osx's openssl.
After installing brew openssl, it works.

**Comment by grizzlydev-sarl** [comment]
Works on macOS 10.14.1
```
$ openssl version
LibreSSL 2.6.4
```
(Libressl 2.6.4 was released on December 19th, 2017).

Doesn't work on macOS 10.8.5
```
$ openssl version
OpenSSL 0.9.8y 5 Feb 2013
```

I'm pretty sure the problem is openssl/libressl. Some versions seem to not be able to handle the newer intermediate certificates.

**Comment by matteocorti** [comment]
macOS 10.8 and OpenSSL 0.9.8 are no longer supported.

**Pull request merged**
